services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "55432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: "dpage/pgadmin4:latest"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_DEFAULT_EMAIL=eppy_92@mail.ru
    ports:
      - "55433:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin: